services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: astro-backend
    restart: unless-stopped
    networks:
      - web
    environment:
      - TZ=Europe/Prague
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.astro-backend.rule=Host(`api.astro.jaroslav.tech`)"
      - "traefik.http.routers.astro-backend.entrypoints=websecure"
      - "traefik.http.routers.astro-backend.tls.certresolver=myresolver"
      - "traefik.http.services.astro-backend.loadbalancer.server.port=80"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://api.astro.jaroslav.tech
    container_name: astro-frontend
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.astro-frontend.rule=Host(`astro.jaroslav.tech`)"
      - "traefik.http.routers.astro-frontend.entrypoints=websecure"
      - "traefik.http.routers.astro-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.astro-frontend.loadbalancer.server.port=80"

networks:
  web:
    external: true
